formation_formation:
    resource: "@FormationFormationBundle/Controller/"
    type:     annotation
    prefix:   /
formindex:
    resource: "@FormationFormationBundle/Controller/"
    type:     annotation
    prefix:   /

